export const minimalManifest = {
  id: "minimal",
  name: "Minimal Zinc",
  version: "1.0.0",
  description: "Monochromatic architectural zinc surfaces with pristine contrast",
  author: "Syncly Team",
  license: "MIT",
  type: "builtin",
  modes: {
    dark: {
      tokens: {
        "--bg": "#18181B",
        "--surface": "#27272A",
        "--surface-2": "#3F3F46",
        "--surface-active": "#52525B",
        "--fg": "#FAFAFA",
        "--fg-secondary": "#E4E4E7",
        "--muted": "#A1A1AA",
        "--muted-2": "#71717A",
        "--border": "#3F3F46",
        "--border-strong": "#52525B",
        "--accent": "#D4D4D8",
        "--accent-primary": "#FFFFFF",
        "--accent-dark": "#A1A1AA",
        "--accent-soft": "rgba(255, 255, 255, 0.12)",
        "--on-accent": "#18181B",
      },
      aura: {
        enabled: true,
        layer1: null,
        layer2: null,
        layer3: null,
        grain: {
          enabled: true,
          opacity: 0.05,
          mixBlendMode: "overlay",
        },
      },
      customCss: "",
    },
    light: {
      tokens: {
        "--bg": "#FFFFFF",
        "--surface": "#F4F4F5",
        "--surface-2": "#E4E4E7",
        "--surface-active": "#D4D4D8",
        "--fg": "#09090B",
        "--fg-secondary": "#18181B",
        "--muted": "#52525B",
        "--muted-2": "#71717A",
        "--border": "#E4E4E7",
        "--border-strong": "#D4D4D8",
        "--accent": "#18181B",
        "--accent-primary": "#09090B",
        "--accent-dark": "#000000",
        "--accent-soft": "rgba(24, 24, 27, 0.08)",
        "--on-accent": "#FFFFFF",
      },
      aura: {
        enabled: true,
        layer1: null,
        layer2: null,
        layer3: null,
        grain: {
          enabled: true,
          opacity: 0.03,
          mixBlendMode: "overlay",
        },
      },
      customCss: "",
    },
  },
};
