export const nordManifest = {
  id: "nord",
  name: "Nordic Frost",
  version: "1.0.0",
  description: "Arctic polar night palette with crystalline frost teal and glacier accents",
  author: "Syncly Team",
  license: "MIT",
  type: "builtin",
  modes: {
    dark: {
      tokens: {
        "--bg": "#2E3440",
        "--surface": "#3B4252",
        "--surface-2": "#434C5E",
        "--surface-active": "#4C566A",
        "--fg": "#ECEFF4",
        "--fg-secondary": "#E5E9F0",
        "--muted": "#D8DEE9",
        "--muted-2": "#8892B0",
        "--border": "#434C5E",
        "--border-strong": "#4C566A",
        "--accent": "#88C0D0",
        "--accent-primary": "#81A1C1",
        "--accent-dark": "#5E81AC",
        "--accent-soft": "rgba(136, 192, 208, 0.16)",
        "--on-accent": "#2E3440",
      },
      aura: {
        enabled: true,
        layer1: {
          background: "radial-gradient(60% 60% at 50% 100%, rgba(136, 192, 208, 0.4) 0%, rgba(46, 52, 64, 0) 100%)",
          mixBlendMode: "screen",
          filter: "blur(90px)",
        },
        layer2: null,
        layer3: null,
        grain: {
          enabled: true,
          opacity: 0.05,
          mixBlendMode: "overlay",
        },
      },
      customCss: "",
    },
    light: {
      tokens: {
        "--bg": "#ECEFF4",
        "--surface": "#FFFFFF",
        "--surface-2": "#E5E9F0",
        "--surface-active": "#D8DEE9",
        "--fg": "#2E3440",
        "--fg-secondary": "#3B4252",
        "--muted": "#4C566A",
        "--muted-2": "#5E81AC",
        "--border": "#D8DEE9",
        "--border-strong": "#B8C5D6",
        "--accent": "#5E81AC",
        "--accent-primary": "#4A6D96",
        "--accent-dark": "#3B5373",
        "--accent-soft": "rgba(94, 129, 172, 0.12)",
        "--on-accent": "#FFFFFF",
      },
      aura: {
        enabled: true,
        layer1: {
          background: "radial-gradient(60% 60% at 50% 100%, rgba(129, 161, 193, 0.25) 0%, rgba(236, 239, 244, 0) 100%)",
          mixBlendMode: "multiply",
          filter: "blur(90px)",
        },
        layer2: null,
        layer3: null,
        grain: {
          enabled: true,
          opacity: 0.03,
          mixBlendMode: "overlay",
        },
      },
      customCss: "",
    },
  },
};
