export const roseGoldManifest = {
  id: "rose_gold",
  name: "Rose Gold",
  version: "1.0.0",
  description: "Kogane Momo warm gradient aura with champagne and rose blush tones",
  author: "Syncly Team",
  license: "MIT",
  type: "builtin",
  modes: {
    dark: {
      tokens: {
        "--bg": "#171115",
        "--surface": "#221920",
        "--surface-2": "#2E222C",
        "--surface-active": "#3F2F3C",
        "--fg": "#FDF2F4",
        "--fg-secondary": "#F5D6DE",
        "--muted": "#B38E9B",
        "--muted-2": "#876472",
        "--border": "#422F3C",
        "--border-strong": "#5C4153",
        "--accent": "#F472B6",
        "--accent-primary": "#DB2777",
        "--accent-dark": "#BE185D",
        "--accent-soft": "rgba(244, 114, 182, 0.15)",
        "--on-accent": "#FFFFFF",
      },
      aura: {
        enabled: true,
        layer1: {
          background: "linear-gradient(180deg in oklab, #FFF0DE 8.3%, #FFDCC0 25.0%, #FBC1A8 41.7%, #EDA9A8 58.3%, #B891A9 75.0%, #4E5A86 91.7%)",
          filter: "blur(5px)",
          inset: "-10px",
        },
        layer2: null,
        layer3: null,
        grain: {
          enabled: true,
          opacity: 0.05,
          mixBlendMode: "overlay",
        },
      },
      customCss: "",
    },
    light: {
      tokens: {
        "--bg": "#FFF5F5",
        "--surface": "#FFFFFF",
        "--surface-2": "#FEE2E2",
        "--surface-active": "#FECACA",
        "--fg": "#2A0E18",
        "--fg-secondary": "#4C1D2C",
        "--muted": "#884A5F",
        "--muted-2": "#A5697D",
        "--border": "#FCD0DC",
        "--border-strong": "#F8A8BE",
        "--accent": "#BE185D",
        "--accent-primary": "#9D174D",
        "--accent-dark": "#831843",
        "--accent-soft": "rgba(190, 24, 93, 0.10)",
        "--on-accent": "#FFFFFF",
      },
      aura: {
        enabled: true,
        layer1: {
          background: "linear-gradient(180deg in oklab, #FFF0DE 8.3%, #FFDCC0 25.0%, #FBC1A8 41.7%, #EDA9A8 58.3%, #B891A9 75.0%, #4E5A86 91.7%)",
          filter: "blur(5px)",
          inset: "-10px",
        },
        layer2: null,
        layer3: null,
        grain: {
          enabled: true,
          opacity: 0.03,
          mixBlendMode: "overlay",
        },
      },
      customCss: "",
    },
  },
};
