export const sageManifest = {
  id: "sage",
  name: "Sage Botanical",
  version: "1.0.0",
  description: "Calm herbal matcha and cedar forest tones with soothing organic warmth",
  author: "Syncly Team",
  license: "MIT",
  type: "builtin",
  modes: {
    dark: {
      tokens: {
        "--bg": "#101713",
        "--surface": "#17221C",
        "--surface-2": "#203028",
        "--surface-active": "#2C4237",
        "--fg": "#F2F7F4",
        "--fg-secondary": "#D4E4DC",
        "--muted": "#8BA698",
        "--muted-2": "#617B6E",
        "--border": "#2A3F34",
        "--border-strong": "#3D5A4B",
        "--accent": "#52B788",
        "--accent-primary": "#2D6A4F",
        "--accent-dark": "#1B4332",
        "--accent-soft": "rgba(82, 183, 136, 0.15)",
        "--on-accent": "#FFFFFF",
      },
      aura: {
        enabled: true,
        layer1: {
          background: "radial-gradient(60% 60% at 50% 100%, rgba(82, 183, 136, 0.35) 0%, rgba(16, 23, 19, 0) 100%)",
          mixBlendMode: "screen",
          filter: "blur(90px)",
        },
        layer2: null,
        layer3: null,
        grain: {
          enabled: true,
          opacity: 0.05,
          mixBlendMode: "overlay",
        },
      },
      customCss: "",
    },
    light: {
      tokens: {
        "--bg": "#F4F8F5",
        "--surface": "#FFFFFF",
        "--surface-2": "#E8F1EB",
        "--surface-active": "#D4E4DA",
        "--fg": "#122119",
        "--fg-secondary": "#1E3629",
        "--muted": "#4A6B59",
        "--muted-2": "#678B77",
        "--border": "#D1E2D7",
        "--border-strong": "#A8C7B3",
        "--accent": "#2D6A4F",
        "--accent-primary": "#1B4332",
        "--accent-dark": "#081C15",
        "--accent-soft": "rgba(45, 106, 79, 0.10)",
        "--on-accent": "#FFFFFF",
      },
      aura: {
        enabled: true,
        layer1: {
          background: "radial-gradient(60% 60% at 50% 100%, rgba(45, 106, 79, 0.18) 0%, rgba(244, 248, 245, 0) 100%)",
          mixBlendMode: "multiply",
          filter: "blur(80px)",
        },
        layer2: null,
        layer3: null,
        grain: {
          enabled: true,
          opacity: 0.03,
          mixBlendMode: "overlay",
        },
      },
      customCss: "",
    },
  },
};
