export const skyDeepSeaManifest = {
  id: "sky_deep_sea",
  name: "Sky Deep Sea",
  version: "1.0.0",
  description: "Oceanic sky atmospheric aura with refreshing aquamarine and deep sea cyan",
  author: "Syncly Team",
  license: "MIT",
  type: "builtin",
  modes: {
    dark: {
      tokens: {
        "--bg": "#08141E",
        "--surface": "#0E1E2B",
        "--surface-2": "#162B3D",
        "--surface-active": "#1E3A52",
        "--fg": "#EDF6FC",
        "--fg-secondary": "#D0E5F5",
        "--muted": "#7EA2BF",
        "--muted-2": "#527694",
        "--border": "#1E364B",
        "--border-strong": "#2A4B67",
        "--accent": "#0EA5E9",
        "--accent-primary": "#0284C7",
        "--accent-dark": "#0369A1",
        "--accent-soft": "rgba(14, 165, 233, 0.15)",
        "--on-accent": "#FFFFFF",
      },
      aura: {
        enabled: true,
        layer1: {
          background: "linear-gradient(180deg in oklab, #C7F2EC 12.5%, #6FC2C4 37.5%, #3E8FA8 62.5%, #2A5E8C 87.5%)",
          filter: "blur(5px)",
          inset: "-10px",
        },
        layer2: null,
        layer3: null,
        grain: {
          enabled: true,
          opacity: 0.05,
          mixBlendMode: "overlay",
        },
      },
      customCss: "",
    },
    light: {
      tokens: {
        "--bg": "#F0F9FF",
        "--surface": "#FFFFFF",
        "--surface-2": "#E0F2FE",
        "--surface-active": "#BAE6FD",
        "--fg": "#0C2338",
        "--fg-secondary": "#163B5C",
        "--muted": "#416788",
        "--muted-2": "#5A82A6",
        "--border": "#BAE6FD",
        "--border-strong": "#7DD3FC",
        "--accent": "#0369A1",
        "--accent-primary": "#075985",
        "--accent-dark": "#0C4A6E",
        "--accent-soft": "rgba(3, 105, 161, 0.10)",
        "--on-accent": "#FFFFFF",
      },
      aura: {
        enabled: true,
        layer1: {
          background: "linear-gradient(180deg in oklab, #C7F2EC 12.5%, #6FC2C4 37.5%, #3E8FA8 62.5%, #2A5E8C 87.5%)",
          filter: "blur(5px)",
          inset: "-10px",
        },
        layer2: null,
        layer3: null,
        grain: {
          enabled: true,
          opacity: 0.03,
          mixBlendMode: "overlay",
        },
      },
      customCss: "",
    },
  },
};
