export const solidManifest = {
  id: "solid",
  name: "Minimal Solid",
  version: "1.0.0",
  description: "Clean distraction-free solid color backgrounds with focused clarity",
  author: "Syncly Team",
  license: "MIT",
  type: "builtin",
  modes: {
    dark: {
      tokens: {
        "--bg": "#0A0A0B",
        "--surface": "#131315",
        "--surface-2": "#1C1C1F",
        "--surface-active": "#28282D",
        "--fg": "#EEEEF0",
        "--fg-secondary": "#D5D5D9",
        "--muted": "#888891",
        "--muted-2": "#62626B",
        "--border": "#24242A",
        "--border-strong": "#383842",
        "--accent": "#6366F1",
        "--accent-primary": "#4F46E5",
        "--accent-dark": "#4338CA",
        "--accent-soft": "rgba(99, 102, 241, 0.14)",
        "--on-accent": "#FFFFFF",
      },
      aura: {
        enabled: true,
        layer1: null,
        layer2: null,
        layer3: null,
        grain: {
          enabled: true,
          opacity: 0.05,
          mixBlendMode: "overlay",
        },
      },
      customCss: "",
    },
    light: {
      tokens: {
        "--bg": "#F9FAFB",
        "--surface": "#FFFFFF",
        "--surface-2": "#F3F4F6",
        "--surface-active": "#E5E7EB",
        "--fg": "#111827",
        "--fg-secondary": "#1F2937",
        "--muted": "#4B5563",
        "--muted-2": "#6B7280",
        "--border": "#E5E7EB",
        "--border-strong": "#D1D5DB",
        "--accent": "#4F46E5",
        "--accent-primary": "#4338CA",
        "--accent-dark": "#3730A3",
        "--accent-soft": "rgba(79, 70, 229, 0.10)",
        "--on-accent": "#FFFFFF",
      },
      aura: {
        enabled: true,
        layer1: null,
        layer2: null,
        layer3: null,
        grain: {
          enabled: true,
          opacity: 0.03,
          mixBlendMode: "overlay",
        },
      },
      customCss: "",
    },
  },
};
